"""Add site monitoring support

Revision ID: 3ca80e78445a
Revises: 
Create Date: 2025-03-19 01:05:50.900363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ca80e78445a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_performance_metrics_id', table_name='performance_metrics')
    op.drop_index('ix_performance_metrics_url', table_name='performance_metrics')
    op.drop_table('performance_metrics')
    op.add_column('request_metrics', sa.Column('site_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_request_metrics_site_id'), 'request_metrics', ['site_id'], unique=False)
    op.add_column('weekly_averages', sa.Column('site_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_weekly_averages_site_id'), 'weekly_averages', ['site_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_averages_site_id'), table_name='weekly_averages')
    op.drop_column('weekly_averages', 'site_id')
    op.drop_index(op.f('ix_request_metrics_site_id'), table_name='request_metrics')
    op.drop_column('request_metrics', 'site_id')
    op.create_table('performance_metrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('request_time_ms', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('error', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='performance_metrics_pkey')
    )
    op.create_index('ix_performance_metrics_url', 'performance_metrics', ['url'], unique=False)
    op.create_index('ix_performance_metrics_id', 'performance_metrics', ['id'], unique=False)
    # ### end Alembic commands ###
