"""Add site_permissions field to User model

Revision ID: 7035ca1364eb
Revises: 3ca80e78445a
Create Date: 2025-03-19 16:30:44.186813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7035ca1364eb'
down_revision: Union[str, None] = '3ca80e78445a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('site_permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='comment',
               existing_nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='comment',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               comment='comment',
               existing_nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               comment='comment',
               existing_nullable=True)
    op.drop_column('users', 'site_permissions')
    # ### end Alembic commands ###
